<a href="https://colab.research.google.com/github/Bishalroybd/Bishalroybd/blob/main/pytorchlearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np


lists


In [ ]:
my_list = [1,2,3,4,5],[6,7,8,9,10]
my_list

([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])

numpy arrays

In [ ]:
np1 =np.random.rand(3,4)
np1

array([[0.52991542, 0.08265195, 0.71329371, 0.37290432],
       [0.81535672, 0.33431138, 0.55832257, 0.14718268],
       [0.5747956 , 0.80307302, 0.11367867, 0.22119001]])

In [ ]:
np1.dtype

dtype('float64')

tensors

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d


tensor([[ 0.0078, -0.4502,  1.2133, -0.3397],
        [ 0.7417,  0.2426, -0.1751,  1.7627],
        [-1.9632, -0.1890, -1.0265,  0.4459]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# create tensor out of numpy arrays
my_tensor = torch.tensor(np1)
my_tensor


tensor([[0.5299, 0.0827, 0.7133, 0.3729],
        [0.8154, 0.3343, 0.5583, 0.1472],
        [0.5748, 0.8031, 0.1137, 0.2212]], dtype=torch.float64)